### PR TITLE
Issue #6 solution

### PR DESCRIPTION
**Pull request by m-spyratos**

### CODE REVIEW

**Comment by alfredkam** [comment]
Hi @m-spyratos, the problem you raised is indeed an issue.  But the changes you made seems to break the travis ci test.  Could you resolve it then i can merge it?

**Comment by m-spyratos** [comment]
Sorry about the rushed pull request. I just realized that another issue arose. I'm doing some tests right now myself, but I am not sure if I am going to have the time for another pull request.

**Comment by alfredkam** [comment]
LGTM

**Comment by alfredkam** [comment]
published @0.1.2

**Pull request merged**
